select * from public.dimcustomers
select * from public.dimproducts
select * from public.factorderitems
select * from public.factorders
select * from public.factpayment

-- 1. How many total orders has UrbanCart received so far?
select 
count("order_id") as total_orders
from public.factorders
-- 2. Which cities generate the highest number of orders & revenue?

select 
-- distinct c.customer_id,
-- c.full_name,
distinct city,
 -- o.order_id,

-- count(distinct o.order_id),
sum(oi.quantity) as total_quantity,
sum(p.unit_price*oi.quantity) as total_revenue

from public.dimcustomers as c
join public.factorders as o on c.customer_id=o.customer_id
join public.factorderitems as oi on oi.order_id=o.order_id
join public.dimproducts as p on p.product_id=oi.product_id
group by 1
order by 3 desc

-- 3. What percent of total customers uses gmail?
with gmail_cus as 
(
select 
count(customer_id) as gmail_cus,
( select
count(customer_id)
from public.dimcustomers) as total_cus

from public.dimcustomers
where email ilike('%gmail%')
)
select
round((gmail_cus::numeric/total_cus::numeric)*100,0) as percentage_user
from gmail_cus

-- 4. What is the monthly trend of total orders over time?
with MoM as 
(select 
O.order_date,
Oi.quantity
from public.factorderitems as oi
left join public.factorders as o on oi.order_id=o.order_id)
select 
to_char(order_date::date , 'month') as month,
sum(quantity) as total_orders
from MoM
group by 1 
order by 1 desc

-- 6. What is the total revenue generated by UrbanCart?
select
sum(oi.quantity*p.unit_price) :: numeric as total_revenue
from public.factorderitems as oi
left join public.dimproducts as p on oi.product_id=p.product_id

-- 7. Which product categories contribute the most to total revenue?
with category as
(
select 
oi.*,
p.*
from public.dimproducts as p
left join public.factorderitems as oi on p.product_id=oi.product_id
)
select 
category,
sum(quantity*unit_price) :: numeric as revenue
from category
group by 1
order by 2 desc

-- 8. Which individual products generate the highest revenue?

with high_rev_pro as
(
select 
oi.*,
p.*
from public.dimproducts as p
left join public.factorderitems as oi on p.product_id=oi.product_id
)
select 
product_name,

sum(quantity*unit_price) :: numeric as revenue
from high_rev_pro
group by 1
order by 2 desc


-- 9. What is the average order value (AOV) and Average Basket Size?

with cte1 as
(
select 
oi.*,
p.*
from public.dimproducts as p
left join public.factorderitems as oi on p.product_id=oi.product_id
)
Select
sum(quantity*unit_price) :: numeric as total_rev,
count(distinct order_id) as total_order,
SUM(quantity) AS total_quantiy,
round(sum(quantity*unit_price) :: numeric/count(distinct order_id),2) as AOV,
SUM(quantity)/count(distinct order_id) as average_basket
from cte1

-- 10. Which products are at risk of stock-out 
-- due to high sales volume and low inventory?

with stock as
(
select 
oi.*,
p.*
from public.dimproducts as p
left join public.factorderitems as oi on p.product_id=oi.product_id
),
status as 
(
select
product_name,
stock,
sum(quantity) as sold
from stock
group by 1,2
order by 3 desc
)
select
*,
case when stock > sold then 'safe'
when sold>stock then 'at_risk'
else 'will run out soon' end as status
from status

-- 11. Which customers contribute the highest total revenue?

select
distinct c.customer_id,
c.full_name,
sum(oi.quantity*p.unit_price) :: numeric as total_revenue
from public.factorderitems as oi
left join public.dimproducts as p on oi.product_id=p.product_id
left join public.factorders as o on oi.order_id=o.order_id
left join public.dimcustomers as c on c.customer_id=o.customer_id
group by 1,2
order by 3 desc

-- 12. Generate a list of cancellation rate by city;
with cancel as 
(select 
c.city,
count(o.status) as cancel_order,
(select count(distinct order_id) from public.factorders) as total_order
from public.factorders as o

left join public.dimcustomers as c on o.customer_id=c.customer_id
where status= 'Cancelled'
group by 1
order by 2 desc)
select 
*,
round((cancel_order::numeric/total_order::numeric)*100,2) as cancellation_rate
from cancel;

-- the cancellation rate for customers.
with cancel as 
( 
select 
 distinct c.customer_id,
c.full_name,
count(o.status) as cancel_order,
(select count(distinct order_id) from public.factorders) as total_order
from public.factorders as o

left join public.dimcustomers as c on o.customer_id=c.customer_id
where status= 'Cancelled'
group by 1,2
order by 2 desc)
select 
*,
round((cancel_order::numeric/total_order::numeric)*100,2) as cancellation_rate
from cancel;


-- 13.Do male and female customers show different purchasing patterns by category?
with cte1 as
(
select
c.gender,
p.category,
oi.quantity
from public.factorderitems as oi
left join public.dimproducts as p on oi.product_id=p.product_id
left join public.factorders as o on oi.order_id=o.order_id
left join public.dimcustomers as c on c.customer_id=o.customer_id

order by 1
)
select
category,
SUM(case when gender='Male' then quantity
else null end) as Male,

SUM( case when gender='Female' then quantity
else null end) as Female

FROM CTE1
group by 1


-- 14. How does customer purchasing behavior change over time since account creation?


with cte1 as 
(select
c.customer_id,full_name,created_at::date,
coalesce (c.created_at::date,min(o.order_date::date)) as created_account,
sum(oi.quantity*p.unit_price) as revenue

from public.dimcustomers as c
left join public.factorders as o on c.customer_id=o.customer_id
left join public.factorderitems as oi on oi.order_id=o.order_id
left join public.dimproducts as p on p.product_id=oi.product_id
group by 1,2,3
order by 1 asc
),
cte2 as
(
select 
ct.*,
fo.order_date::date
from cte1 as ct
left join public.factorders as fo on ct.customer_id=fo.customer_id
),
cte3 as 
(select
*,
to_char( created_account,'month') as created_month,
trim(to_char(order_date::date,'month')) as order_month
from cte2)
select 
distinct customer_id,
full_name,
created_month,
sum(case when order_month='september' then revenue else 0 end)as september,
sum(case when order_month='october' then revenue else 0 end)as october,
sum(case when order_month='november' then revenue else 0 end)as november,
sum(case when order_month='december' then revenue else 0 end)as december
from cte3
group by 1,2,3
order by 1 asc

-- 15. Generate a list of customers who ordered in October but didn’t order in December.
with cte1 as 
(select 
c.customer_id,
o.order_date::date
from public.dimcustomers as c
left join public.factorders as o on c.customer_id=o.customer_id
left join public.factorderitems as oi on oi.order_id=o.order_id
left join public.dimproducts as p on p.product_id=oi.product_id
) ,
 october as 
(select
*
from cte1
where (order_date::date)  between '2025-10-01' and '2025-10-31'),
december as 
(select *
from cte1 
where (order_date::date) between '2025-12-01' and '2025-12-31')
select
distinct s.customer_id as october_order_customerid,

d.order_date as december_order
from october as s
left join december as d on d.customer_id=s.customer_id
where d.order_date is null
order by s.customer_id asc

-- 16. Generate a list of customers who ordered both in October & December.
with cte1 as 
(select 
c.customer_id,
o.order_date::date
from public.dimcustomers as c
left join public.factorders as o on c.customer_id=o.customer_id
left join public.factorderitems as oi on oi.order_id=o.order_id
left join public.dimproducts as p on p.product_id=oi.product_id
),
 october as 
(select
*
from cte1
where (order_date::date)  between '2025-10-01' and '2025-10-31'),
december as 
(select *
from cte1 
where (order_date::date) between '2025-12-01' and '2025-12-31'),
cte2 as 
(
select
distinct s.customer_id,
s.order_date,
d.order_date
from october as s
join december as d on d.customer_id=s.customer_id
)
select 
distinct customer_id as oct_and_dec_customer
from cte2

-- 17. Which payment methods are used most frequently?
select 
method,
count(order_id)
from public.factpayment
group by 1
order by 2 desc

-- 18. Is there any relationship between payment method and order status?

select 
p.method,
o.status,
count(p.order_id) as orders
from public.factorders as o
join public.factpayment as p on o.order_id=p.order_id
group by 1,2
order by 2 asc

-- 19.Do certain cities prefer specific payment methods?
with cte as 
(select 
c.city,
fp.method,
o.order_id
from public.factorders as o
join public.dimcustomers as c on o.customer_id=c.customer_id
join public.factpayment as fp on o.order_id=fp.order_id
)
select 
city,
count (case when method='Nagad' then order_id else null end) as Nagad,
count (case when method='COD' then order_id else null end) as COD,
count (case when method='bKash' then order_id else null end) as bKash,
count (case when method='Debit Card' then order_id else null end) as Debit_Card,
count (case when method='Credit Card' then order_id else null end) as Credit_Card
FROM cte
group by 1

-- 20. Are higher-value orders associated with specific payment methods?
with cte1 as 
(select
O.order_id,
fp.method,
sum(oi.quantity*p.unit_price) as revenue

from public.dimcustomers as c
left join public.factorders as o on c.customer_id=o.customer_id
left join public.factorderitems as oi on oi.order_id=o.order_id
left join public.dimproducts as p on p.product_id=oi.product_id
LEFT JOIN public.factpayment AS fp on o.order_id=fp.order_id
group by 1,2
order by 1 asc
),
cte2 as 
(select 
*,
ntile(5) over(order by revenue asc ) as higher_value_score
from cte1),
cte3 as
(
select * from cte2 
where higher_value_score='5' 
)
select
method,
count (revenue)
from cte3
group by 1
order by 2 desc
-- 21. What is the average number of items per order by payment method?
with cte as 
(select 
c.city,
fp.method,
o.order_id
from public.factorders as o
join public.dimcustomers as c on o.customer_id=c.customer_id
join public.factpayment as fp on o.order_id=fp.order_id
),
cte1 as 
(select 
count (case when method='Nagad' then order_id else null end) as Nagad,
count (case when method='COD' then order_id else null end) as COD,
count (case when method='bKash' then order_id else null end) as bKash,
count (case when method='Debit Card' then order_id else null end) as Debit_Card,
count (case when method='Credit Card' then order_id else null end) as Credit_Card
FROM cte
),
cte2 as
(
select 
oi.quantity,
fp.method,
oi.order_id
from public.factorderitems as oi
join public.factpayment as fp on oi.order_id=fp.order_id
),
cte3 as
(select  
sum (case when method='Nagad' then quantity else null end) as Nagad,
sum (case when method='COD' then quantity else null end) as COD,
sum (case when method='bKash' then quantity else null end) as bKash,
sum (case when method='Debit Card' then quantity else null end) as Debit_Card,
sum (case when method='Credit Card' then quantity else null end) as Credit_Card
from cte2
)
select 
round(c3.Nagad::numeric/c1.Nagad::numeric,0) as average_nagad,
round(c3.COD::numeric/c1.COD::numeric,0) as average_COD,
round(c3.bKash::numeric/c1.bKash::numeric,0) as average_bKash,
round(c3.Debit_Card::numeric/c1.Debit_Card::numeric,0) as average_Debit_Card,
round(c3.Credit_Card::numeric/c1.Credit_Card::numeric,0) as average_Credit_Card
from cte1 as c1
cross join cte3 as c3

-- 22.Create a list to show the difference between the category average price and product’s price for all the products.


with cte as
(
select 
 category,
count(product_name) as total_pro,
sum(unit_price) as total_price
from public.dimproducts
group by 1
),
cte1 as
(
select 
*,
round(total_price::numeric/total_pro::numeric,0) as cat_avg_price
from cte
)
select 
p.product_name,
p.category,
p.unit_price,
c.cat_avg_price,
round((p.unit_price - c.cat_avg_price)::numeric, 2) as price_diff
from public.dimproducts as p
join cte1 as c on p.category = c.category
order by p.category desc

-- 23. Which product pairs are most frequently purchased together in the same order?
with cte as
(
select 
fo1.order_id,
fo1.product_id,
p1.product_name as p1,
fo2.product_id,
p2.product_name as p2

from public.factorderitems as fo1

 left join public.factorderitems as fo2 on fo1.order_id=fo2.order_id and fo1.product_id<fo2.product_id
left join public.dimproducts as p1 on fo1.product_id=p1.product_id
left join public.dimproducts as p2 on fo2.product_id=p2.product_id
where fo2.product_id  is not null

),
 cte1 as
(
select
order_id,
concat(p1,',',p2) as product_pairs
from cte
)
select
product_pairs,
count(product_pairs) as total_ordered
from cte1
group by 1
order by 2 desc
limit 20
-- 24. Which product pairs generate the highest total revenue when sold together?
with cte as
(
select 
fo1.order_id,
fo1.product_id,
p1.product_name as p1,
(fo1.quantity*p1.unit_price) as price1,
fo2.product_id,
p2.product_name as p2,
(fo2.quantity*p2.unit_price) as price2


from public.factorderitems as fo1

 left join public.factorderitems as fo2 on fo1.order_id=fo2.order_id and fo1.product_id<fo2.product_id
left join public.dimproducts as p1 on fo1.product_id=p1.product_id
left join public.dimproducts as p2 on fo2.product_id=p2.product_id
where fo2.product_id  is not null

),
 cte1 as
(
select
order_id,
concat(p1,',',p2) as product_pairs,
(price1+price2) as price
from cte
)
select
product_pairs,
count(product_pairs) as total_orders,
sum(price) as total_revenue
from cte1
group by 1
order by 3 desc
LIMIT 10

-- 25. Generate a daily report containing the columns Date, Total Orders, Total Items,
--  Completed Orders, Cancelled Orders, Total Revenue
select
distinct o.order_date::date,
count(o.order_id) as total_order,
sum(oi.quantity) as total_item,
sum(oi.quantity*p.unit_price) as total_revenue,
count(case when status='Completed' then o.order_id else null end) as Completed,
count(case when status='Cancelled' then o.order_id else null end) as Cancelled
from public.factorders as o 
join public.factorderitems as oi on o.order_id=oi.order_id
join public.dimproducts as p on p.product_id=oi.product_id
join public.factpayment as fp on fp.order_id=o.order_id

group by 1
order by 1 asc














